# Generated by Django 4.2.6 on 2023-10-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0003_classmodel_schoolmodel_studentmodel_subjectmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubjectmodel',
            old_name='marks',
            new_name='percentage',
        ),
    ]
