# Generated by Django 4.2.6 on 2023-10-27 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0005_remove_schoolmodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='exam_certificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to='exam_certificates/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='associated_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edudealio.classmodel'),
        ),
    ]
