# Generated by Django 4.2.6 on 2023-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0006_alter_studentmodel_exam_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='associated_class',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='semester',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='subjects',
            field=models.ManyToManyField(through='edudealio.StudentSubjectModel', to='edudealio.subjectmodel'),
        ),
    ]
