# Generated by Django 4.2.6 on 2023-10-27 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0007_remove_studentmodel_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='custom_school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsubjectmodel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
