# Generated by Django 4.2.6 on 2023-10-28 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0008_studentmodel_custom_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDashboardDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('uploads', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('offers_avail', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edudealio.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAvailOffersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_offer_avail', models.DateField(auto_now=True)),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edudealio.offersmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edudealio.studentmodel')),
            ],
        ),
    ]
