# Generated by Django 4.2.6 on 2023-10-29 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0009_offersmodel_studentdashboarddatamodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdashboarddatamodel',
            old_name='points',
            new_name='total_points',
        ),
        migrations.AddField(
            model_name='studentdashboarddatamodel',
            name='active_points',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
