# Generated by Django 4.2.6 on 2023-10-30 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edudealio', '0011_studentavailoffersmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdashboarddatamodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='studentavailoffersmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdashboarddatamodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
