# Generated by Django 4.2.6 on 2023-10-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0012_remove_studentdashboarddatamodel_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentavailoffersmodel',
            name='student',
        ),
    ]
