# Generated by Django 4.2.6 on 2023-10-31 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edudealio', '0015_alter_studentdashboarddatamodel_active_points_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentPoints',
            new_name='StudentPointsModel',
        ),
    ]
