# Generated by Django 4.2.6 on 2023-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0016_rename_studentpoints_studentpointsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='exam_certificate',
            field=models.FileField(upload_to='files/'),
        ),
    ]
