# Generated by Django 4.2.6 on 2023-10-31 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0018_offersmodel_img_url_offersmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersmodel',
            name='discount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
