# Generated by Django 4.2.6 on 2023-10-31 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edudealio', '0019_alter_offersmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersmodel',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='CouponCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edudealio.offersmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
