# Generated by Django 4.2.6 on 2023-10-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0020_offersmodel_expiry_date_couponcodemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersmodel',
            old_name='expiry_date',
            new_name='validity_period',
        ),
    ]
