# Generated by Django 4.2.6 on 2023-11-07 06:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edudealio', '0023_topicsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('question_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edudealio.classmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TopicsModel',
        ),
    ]
