# Generated by Django 4.2.6 on 2023-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0024_questionarymodel_delete_topicsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpointsmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
