# Generated by Django 4.2.6 on 2023-11-25 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edudealio', '0027_activitymodel_studentcurriculummodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizeTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='studentcurriculummodel',
            name='certificate',
            field=models.FileField(upload_to='curriculum/'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='exam_certificate',
            field=models.FileField(upload_to='academic/'),
        ),
        migrations.CreateModel(
            name='StandardizeTestAchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('certificate', models.FileField(upload_to='standardize/')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edudealio.standardizetestmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
