# Generated by Django 4.2.6 on 2023-12-01 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edudealio', '0029_referral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referral',
            new_name='ReferralModel',
        ),
    ]
