# Generated by Django 4.2.6 on 2023-12-06 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edudealio', '0031_userprofilemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionaryModel',
            new_name='QuestionnaireModel',
        ),
    ]
