# Generated by Django 4.2.6 on 2023-12-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0032_rename_questionarymodel_questionnairemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairemodel',
            name='topic',
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edudealio.subjectmodel'),
        ),
    ]
