# Generated by Django 4.2.6 on 2023-12-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0033_remove_questionnairemodel_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairemodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='topic',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
