# Generated by Django 4.2.6 on 2023-12-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0034_remove_questionnairemodel_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='questionnairemodel',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edudealio.aitopicmodel'),
        ),
    ]
