# Generated by Django 4.2.6 on 2023-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edudealio', '0036_studentsubjectmodel_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectmodel',
            name='added_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
